# ===================================================================
# Real-data Configuration Template
# ===================================================================

# === Functional Data Generation 
mu: 15 # number of basis used to generate data
tau: 256 # number of observations in the functional space [0,1]
p: 64
n_g1: 77
n_g2: 45


# === Reconstruction & Dimensionality Reduction ===
rec_basis_type: "fourier" # type of basis used to rencontrict the data
rec_basis_number: 15 # how many basis are used to reconstrct the data
M: 5  # number of fPC to retain





